apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pv-claim-rwm
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
      #- ReadWriteMany
  resources:
    requests:
      storage: 3Gi

